#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# PR Review Cleanup Script
# Paired with: pr-review-bootstrap.sh
# Orchestrated by: .claude/skills/review-pull-request/SKILL.md
#
# Removes all artifacts generated by pr-review-bootstrap.sh:
#   - documentation/pr-files/pr-{NUMBER}-*                  (diff, files, context, state)
#   - .claude/git-stash/pr-review-{NUMBER}-*.json  (stash metadata)
#   - ../git-stash-storage/pr-review-{NUMBER}-*    (untracked file storage)
# =============================================================================

die() { echo "ERROR: $*" >&2; exit 1; }

PR_NUMBER="${1:-}"
FORCE="${2:-}"

if [[ -z "$PR_NUMBER" ]]; then
  echo "Usage: $0 <PR_NUMBER> [--force]" >&2
  exit 1
fi

if ! echo "$PR_NUMBER" | grep -qE '^[0-9]+$'; then
  die "PR_NUMBER must be numeric, got: $PR_NUMBER"
fi

REPO_ROOT=$(git rev-parse --show-toplevel) || die "Not inside a git repository"
PR_FILES_DIR="${REPO_ROOT}/documentation/pr-files"
STASH_METADATA_DIR="${REPO_ROOT}/.claude/git-stash"
STATE_FILE="${PR_FILES_DIR}/pr-bootstrap-state-${PR_NUMBER}.json"

# Guard: warn if stash hasn't been restored
if [[ -f "$STATE_FILE" && "$FORCE" != "--force" ]]; then
  STASHED=$(jq -r '.stashed // "no"' "$STATE_FILE" 2>/dev/null || echo "no")
  MOVED=$(jq -r '.moved_untracked // "no"' "$STATE_FILE" 2>/dev/null || echo "no")
  if [[ "$STASHED" == "yes" || "$MOVED" == "yes" ]]; then
    STASH_ID_VAL=$(jq -r '.stash_id // ""' "$STATE_FILE" 2>/dev/null || echo "")
    if [[ -n "$STASH_ID_VAL" && -f "${STASH_METADATA_DIR}/${STASH_ID_VAL}.json" ]]; then
      die "Stash has not been restored yet (metadata: ${STASH_ID_VAL}.json). Run 'restore-stashed-changes' first, or pass --force to clean up anyway."
    fi
  fi
fi

# Remove stash metadata files for this PR
if [[ -d "$STASH_METADATA_DIR" ]]; then
  rm -f "${STASH_METADATA_DIR}"/pr-review-"${PR_NUMBER}"-*.json 2>/dev/null || true
fi

# Remove untracked file storage directories for this PR (created outside repo by bootstrap)
STASH_STORAGE_DIR="${REPO_ROOT}/../git-stash-storage"
if [[ -d "$STASH_STORAGE_DIR" ]]; then
  for dir in "${STASH_STORAGE_DIR}"/pr-review-"${PR_NUMBER}"-*; do
    [[ -d "$dir" ]] && rm -rf "$dir"
  done
fi

# Remove all artifacts for this PR
rm -rf "${PR_FILES_DIR}"/pr-"${PR_NUMBER}"-full.diff \
       "${PR_FILES_DIR}"/pr-"${PR_NUMBER}"-files.txt \
       "${PR_FILES_DIR}"/pr-"${PR_NUMBER}"-files/ \
       "${PR_FILES_DIR}"/pr-"${PR_NUMBER}"-context.md \
       "${PR_FILES_DIR}"/pr-"${PR_NUMBER}"-issues.txt \
       "${PR_FILES_DIR}"/pr-bootstrap-state-"${PR_NUMBER}".json 2>/dev/null || true

echo "Cleaned up ${PR_FILES_DIR}/pr-${PR_NUMBER}-* artifacts."
